# Импорты библиотек и загрузки данных

In [1]:
import pandas as pd

In [2]:
train_m = pd.read_parquet(r"data\\train\\train_main_features.parquet")
# train_e = pd.read_parquet(r"data\\train\\train_extra_features.parquet")
train_t = pd.read_parquet(r"data\\train\\train_target.parquet")

In [3]:
test_m = pd.read_parquet(r"data\\test\\test_main_features.parquet")
test_e = pd.read_parquet(r"data\\test\\test_extra_features.parquet")

In [4]:
sample_submit = pd.read_parquet(r"data\\sample_submit.parquet")

# Начальное исследование данных (вход\выход)

In [5]:
sample_submit.head()

,customer_id,predict_1_1,predict_1_2,predict_1_3,predict_1_4,predict_1_5,predict_2_1,predict_2_2,predict_2_3,predict_2_4,...,predict_8_3,predict_9_1,predict_9_2,predict_9_3,predict_9_4,predict_9_5,predict_9_6,predict_9_7,predict_9_8,predict_10_1
0,1750001,-4.559634,-5.490853,-3.682293,-3.696798,-6.377251,-4.698343,-3.925055,-6.864407,-4.644582,...,-3.969470,-5.522536,-2.835501,-3.592803,-5.626597,-4.600432,-0.826411,-2.292409,-4.566064,-0.624437
1,1750002,-4.525017,-5.424643,-3.600475,-3.663936,-6.481639,-4.698258,-3.878170,-6.936742,-4.645305,...,-3.882064,-5.586788,-2.723239,-3.643311,-5.593574,-4.575498,-0.778346,-2.265025,-4.476992,-0.654095
2,1750003,-4.236281,-5.217968,-3.718711,-3.652767,-6.019878,-5.293401,-3.742374,-7.368946,-4.510376,...,-3.915707,-5.821074,-3.501836,-3.764656,-5.877993,-5.007001,-1.049139,-2.805007,-5.363468,-0.362334
3,1750004,-5.107494,-5.747457,-3.870310,-3.988364,-6.613195,-4.781696,-4.434008,-7.223677,-4.649338,...,-4.015814,-5.678406,-2.961717,-3.568433,-5.278345,-4.324995,-0.696825,-2.157653,-4.039829,-0.652303
4,1750005,-4.482090,-5.395573,-3.571668,-3.641002,-6.268344,-4.670509,-3.762274,-6.943392,-4.550145,...,-3.632175,-5.412687,-2.838579,-3.566938,-5.623631,-4.545470,-0.736783,-2.241710,-4.585213,-0.668844

У нас 41 товар\услуга\категория, для которой мы должны выдать число. Это число может быть вероятность покупки, может что-либо другое, как на примере выше, главное это позиция при отранжировании этих числовых значений, так как метрика ROC-AUC.

In [6]:
train_m.head()

,customer_id,cat_feature_1,cat_feature_2,cat_feature_3,cat_feature_4,cat_feature_5,cat_feature_6,cat_feature_7,cat_feature_8,cat_feature_9,...,num_feature_123,num_feature_124,num_feature_125,num_feature_126,num_feature_127,num_feature_128,num_feature_129,num_feature_130,num_feature_131,num_feature_132
0,1000001,1.0,0.0,2.0,1.0,2.0,3.0,2.0,2.0,4.0,...,-0.031281,-0.046146,NaN,-0.445279,NaN,NaN,-0.107666,-0.418616,NaN,NaN
1,1000002,1.0,0.0,0.0,1.0,0.0,3.0,0.0,0.0,0.0,...,-0.031281,-0.046146,-0.10217,1.550722,NaN,NaN,-0.170724,-0.805771,-0.397803,-0.373734
2,1000003,1.0,0.0,0.0,1.0,0.0,3.0,0.0,0.0,4.0,...,-0.031281,-0.046146,NaN,-0.475778,NaN,NaN,-0.170724,-0.602005,-0.397803,-0.373734
3,1000004,1.0,0.0,2.0,1.0,2.0,3.0,2.0,2.0,3.0,...,-0.031281,-0.046146,NaN,-0.475778,0.111196,0.116695,NaN,-0.724265,NaN,NaN
4,1000005,1.0,2.0,0.0,1.0,0.0,3.0,0.0,0.0,2.0,...,NaN,-0.046146,NaN,NaN,NaN,NaN,-0.107666,NaN,-0.397803,-0.373734

У нас есть большая часть категориальных и еще большая числовых признаков. Мы не знаем, какие признаки за что отвечают, но мы можем отследить поведение пользователей отраженное в данных признаках.

Таким образом нам необходимо: поработать над признаками, обучить модель на multi-label задачу, так чтобы для каждой категории выдавалось значение, которое бы выдавало значение, которое можно было бы интерпритировать как вероятность клика, но не обязательно по шкале 0 - 100%, а любой шкале, где будет значение негатива, меньше значения позитива.